//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vaagdevi
{
    using System;
    using System.Collections.Generic;
    
    public partial class fee
    {
        public int ID { get; set; }
        public Nullable<int> Total_fee { get; set; }
        public Nullable<int> Amount_paid { get; set; }
        public Nullable<int> Pending_fee { get; set; }
        public string fee_status { get; set; }
    }
}
