//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vaagdevi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Applied_Physics { get; set; }
        public Nullable<int> Oop { get; set; }
        public Nullable<int> M1 { get; set; }
        public Nullable<int> PS1 { get; set; }
        public Nullable<int> EM1 { get; set; }
        public Nullable<int> AED { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> percentag { get; set; }
    }
}
