//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vaagdevi
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public Nullable<int> sno { get; set; }
        public string Name { get; set; }
        public int ID { get; set; }
    }
}
